apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: listen
      port: {{ .Values.ports.listen }}
      targetPort: {{ .Values.ports.listen }}
    - name: admin
      port: {{ .Values.ports.admin }}
      targetPort: {{ .Values.ports.admin }}