apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          command: ["orderer"]
          env:
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/config

            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"

            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /etc/hyperledger/fabric/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /etc/hyperledger/fabric/tls/ca.crt

            - name: ORDERER_GENERAL_LOCALMSPID
              value: {{ .Values.msp.id }}
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /etc/hyperledger/fabric/msp

            - name: ORDERER_FILELEDGER_LOCATION
              value: /var/hyperledger/production/ledger

            - name: ORDERER_CHANNELPARTICIPATION_ENABLED
              value: "true"

            - name: ORDERER_ADMIN_TLS_ENABLED
              value: "false"
          ports:
            - containerPort: 7050
          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric
              subPath: organizations/{{ .Values.org.address }}/orderers/{{ .Values.name }}.{{ .Values.org.address }}
            - name: ledger-volume
              mountPath: /var/hyperledger/production/ledger
            - name: orderer-config
              mountPath: /etc/hyperledger/fabric/config
      volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: ca-pvc
        - name: ledger-volume
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-ledger-pvc
        - name: orderer-config
          configMap:
            name: orderer-config