apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-tools
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-tools
  template:
    metadata:
      labels:
        app: admin-tools
    spec:
      containers:
        - name: cli
          image: ubuntu:22.04
          command: ["sh", "-c", "--"]
          args:
            - |
              mkdir -p /opt/fabric && cd /opt/fabric && \
              apt update && \
              apt install -y curl unzip ca-certificates bash && \
              curl -sSL https://github.com/hyperledger/fabric/releases/download/v3.1.0/hyperledger-fabric-linux-amd64-3.1.0.tar.gz | tar xz && \
              echo "🧰 Fabric CLI tools are ready! Use kubectl exec to run them."

              cp /etc/hyperledger/fabric/config/createJoin.sh /etc/hyperledger/fabric/createJoin.sh

              sleep infinity
          env:
            - name: PATH
              value: "/opt/fabric/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/config
          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric/organizations
              subPath: organizations
            - name: ca-data
              mountPath: /etc/hyperledger/fabric/admin-client
              subPath: admin-client
            - name: channel-config
              mountPath: /etc/hyperledger/fabric/config
      volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: ca-pvc
        - name: channel-config
          configMap:
            name: channel-config
            defaultMode: 0775  # 👈 This makes it executable