apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 7054
          args:
            - sh
            - -c
            - |
              fabric-ca-server start \
                -b {{ .Values.root.user }}:{{ .Values.root.pass }} \
                -n {{ .Values.ca.name }} \
                --csr.hosts {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local,localhost \
                --tls.enabled \
                --tls.certfile=/etc/hyperledger/fabric-ca-client/tls-ca/{{ .Values.root.user }}/msp/signcerts/cert.pem \
                --tls.keyfile=/etc/hyperledger/fabric-ca-client/tls-ca/{{ .Values.root.user }}/msp/keystore/key.pem \
                -d
          volumeMounts:
            - name: tls-ca-client-data
              mountPath: /etc/hyperledger/fabric-ca-client
            - name: org-ca-server-data
              mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
        - name: tls-ca-client-data
          persistentVolumeClaim:
            claimName: {{ .Values.tls.name }}-client-pvc
        - name: org-ca-server-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-server-pvc