apiVersion: batch/v1
kind: Job
metadata:
  name: org-ca-enrollment
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: org-ca-enrollment
          image: {{ .Values.image }}
          env:
            - name: ORG_DOMAIN
              value: {{ .Values.namespace}}.svc.cluster.local
            - name: FABRIC_CA_CLIENT_HOME
              value: /etc/hyperledger/fabric-ca-client/organizations/{{ .Values.namespace }}.svc.cluster.local
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
          command: [ "sh", "/tmp/enrollment/org-ca-enroll.sh" ]
          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric-ca-client
            - name: ca-data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/{{ .Values.namespace }}/tls
            - name: node-ou-config
              mountPath: /tmp/config
            - name: enrollment
              mountPath: /tmp/enrollment
      restartPolicy: Never
      volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: ca-pvc
        - name: node-ou-config
          configMap:
            name: node-ou-config
        - name: enrollment
          configMap:
            name: tls-ca-enrollment-scripts
            defaultMode: 0775