apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-ca
  template:
    metadata:
      labels:
        app: root-ca
    spec:
      containers:
        - name: root-ca
          image: {{ .Values.image }}
          ports:
            - containerPort: 7054
          args:
            - sh
            - -c
            - |
              fabric-ca-server start -b {{ .Values.user }}:{{ .Values.pass }} -d