apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-pvc
  namespace: admin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: admin-ca-pv
  storageClassName: ""