services:
  graphql-api:
    networks: [ microenergy ]
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    depends_on:
      user-service:
        condition: service_started
      inventory-service:
        condition: service_started
    ports:
      - "${GRAPHQL_API_PORT}:${GRAPHQL_API_PORT}"
    env_file: .env

networks:
  microenergy: {}