mutation PurchaseEnergy ($id: ID!, $capacity: Float!) {
    purchaseEnergy(in: {
        id: $id
        capacity: $capacity
    }) {
        id
        name
        producer {
            first_name
            last_name
        }
        capacity
        price
    }
}
