apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          command: ["peer", "node", "start"]
          env:
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric/config

            - name: CORE_PEER_ID
              value: {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local
            - name: CORE_PEER_NETWORKID
              value: {{ .Values.namespace }}
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_ADDRESS
              value: {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_CHAINCODEADDRESS
              value: {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local:7052

            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/node/msp
            - name: CORE_PEER_LOCALMSPID
              value: {{ .Values.msp.id }}

            - name: CORE_PEER_FILESYSTEMPATH
              value: /var/hyperledger/production

            # TLS Configuration
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/node/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/node/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/node/tls/ca.crt

          ports:
            - containerPort: 7051
            - containerPort: 7052

          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric/node
              subPath: organizations/{{ .Values.org.address }}/peers/{{ .Values.name }}.{{ .Values.org.address }}
            - name: peer-ledger-volume
              mountPath: /var/hyperledger/production
            - name: core-config
              mountPath: /etc/hyperledger/fabric/config
      volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: ca-pvc
        - name: peer-ledger-volume
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-ledger-pvc
        - name: core-config
          configMap:
            name: core-config
