apiVersion: v1
kind: ConfigMap
metadata:
  name: ou-msp-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    NodeOUs:
      Enable: true
      ClientOUIdentifier:
        OrganizationalUnitIdentifier: client
      PeerOUIdentifier:
        OrganizationalUnitIdentifier: peer
      AdminOUIdentifier:
        OrganizationalUnitIdentifier: admin
      OrdererOUIdentifier:
        OrganizationalUnitIdentifier: orderer