apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 7054
          args:
            - sh
            - -c
            - |
              fabric-ca-server start \
                -b {{ .Values.user }}:{{ .Values.pass }} \
                -u http://{{ .Values.root.user }}:{{ .Values.root.pass }}@{{ .Values.root.host }} \
                -d