apiVersion: batch/v1
kind: Job
metadata:
  name: register-identities-{{ .Values.orgName }}
  namespace: fabric
spec:
  template:
    spec:
      containers:
        - name: fabric-ca-client
          image: {{ .Values.ca.image }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Enrolling CA admin..."
              fabric-ca-client enroll \
                -u http://{{ .Values.ca.admin.user }}:{{ .Values.ca.admin.pass }}@ca-{{ .Values.orgName }}.fabric.svc.cluster.local:7054

              echo "Registering org admin..."
              fabric-ca-client register \
                --id.name {{ .Values.registerJob.admin.name }} \
                --id.secret {{ .Values.registerJob.admin.pass }} \
                --id.type admin \
                --id.attrs "hf.Registrar.Roles=client,peer,admin,hf.Revoker=true,role=admin:ecert" \
                -u http://ca-{{ .Values.orgName }}.fabric.svc.cluster.local:7054

              echo "Registering peer identity..."
              fabric-ca-client register \
                --id.name {{ .Values.registerJob.peer.name }} \
                --id.secret {{ .Values.registerJob.peer.pass }} \
                --id.type peer \
                -u http://ca-{{ .Values.orgName }}.fabric.svc.cluster.local:7054

              echo "Enrolling org admin..."
              fabric-ca-client enroll \
                -u http://{{ .Values.registerJob.admin.name }}:{{ .Values.registerJob.admin.pass }}@ca-{{ .Values.orgName }}.fabric.svc.cluster.local:7054 \
                -M /etc/hyperledger/fabric-ca-client/{{ .Values.registerJob.admin.name }}-msp

              echo "Enrolling peer identity..."
              fabric-ca-client enroll \
                -u http://{{ .Values.registerJob.peer.name }}:{{ .Values.registerJob.peer.pass }}@ca-{{ .Values.orgName }}.fabric.svc.cluster.local:7054 \
                -M /etc/hyperledger/fabric-ca-client/{{ .Values.registerJob.peer.name }}-msp
          volumeMounts:
            - name: msp-storage
              mountPath: /etc/hyperledger/fabric-ca-client
      restartPolicy: Never
      volumes:
        - name: msp-storage
          persistentVolumeClaim:
            claimName: {{ .Values.registerJob.peer.name }}-{{ .Values.orgName }}-msp-pvc

  backoffLimit: 1