apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
spec:
  selector:
    app: {{ .Values.container.name }}
  ports:
    - protocol: TCP
      port: 7054
      targetPort: 7054