apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.registerJob.peer.name }}-{{ .Values.orgName }}-msp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi