apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: {{ .Values.namespace }}-ca-pv
  storageClassName: ""
