// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: inventory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InventoryManagement_GetOwnerEnergyResourceList_FullMethodName = "/pb.InventoryManagement/GetOwnerEnergyResourceList"
)

// InventoryManagementClient is the client API for InventoryManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryManagementClient interface {
	GetOwnerEnergyResourceList(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*EnergyResourceList, error)
}

type inventoryManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryManagementClient(cc grpc.ClientConnInterface) InventoryManagementClient {
	return &inventoryManagementClient{cc}
}

func (c *inventoryManagementClient) GetOwnerEnergyResourceList(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*EnergyResourceList, error) {
	out := new(EnergyResourceList)
	err := c.cc.Invoke(ctx, InventoryManagement_GetOwnerEnergyResourceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryManagementServer is the server API for InventoryManagement service.
// All implementations must embed UnimplementedInventoryManagementServer
// for forward compatibility
type InventoryManagementServer interface {
	GetOwnerEnergyResourceList(context.Context, *wrapperspb.StringValue) (*EnergyResourceList, error)
	mustEmbedUnimplementedInventoryManagementServer()
}

// UnimplementedInventoryManagementServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryManagementServer struct {
}

func (UnimplementedInventoryManagementServer) GetOwnerEnergyResourceList(context.Context, *wrapperspb.StringValue) (*EnergyResourceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwnerEnergyResourceList not implemented")
}
func (UnimplementedInventoryManagementServer) mustEmbedUnimplementedInventoryManagementServer() {}

// UnsafeInventoryManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryManagementServer will
// result in compilation errors.
type UnsafeInventoryManagementServer interface {
	mustEmbedUnimplementedInventoryManagementServer()
}

func RegisterInventoryManagementServer(s grpc.ServiceRegistrar, srv InventoryManagementServer) {
	s.RegisterService(&InventoryManagement_ServiceDesc, srv)
}

func _InventoryManagement_GetOwnerEnergyResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryManagementServer).GetOwnerEnergyResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryManagement_GetOwnerEnergyResourceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryManagementServer).GetOwnerEnergyResourceList(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryManagement_ServiceDesc is the grpc.ServiceDesc for InventoryManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.InventoryManagement",
	HandlerType: (*InventoryManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOwnerEnergyResourceList",
			Handler:    _InventoryManagement_GetOwnerEnergyResourceList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
