// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: metering.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Metering_UploadMeteringReading_FullMethodName = "/pb.Metering/UploadMeteringReading"
	Metering_RecordDispatch_FullMethodName        = "/pb.Metering/RecordDispatch"
)

// MeteringClient is the client API for Metering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeteringClient interface {
	UploadMeteringReading(ctx context.Context, opts ...grpc.CallOption) (Metering_UploadMeteringReadingClient, error)
	RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error)
}

type meteringClient struct {
	cc grpc.ClientConnInterface
}

func NewMeteringClient(cc grpc.ClientConnInterface) MeteringClient {
	return &meteringClient{cc}
}

func (c *meteringClient) UploadMeteringReading(ctx context.Context, opts ...grpc.CallOption) (Metering_UploadMeteringReadingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Metering_ServiceDesc.Streams[0], Metering_UploadMeteringReading_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &meteringUploadMeteringReadingClient{stream}
	return x, nil
}

type Metering_UploadMeteringReadingClient interface {
	Send(*Reading) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type meteringUploadMeteringReadingClient struct {
	grpc.ClientStream
}

func (x *meteringUploadMeteringReadingClient) Send(m *Reading) error {
	return x.ClientStream.SendMsg(m)
}

func (x *meteringUploadMeteringReadingClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *meteringClient) RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error) {
	out := new(RecordDispatchResponse)
	err := c.cc.Invoke(ctx, Metering_RecordDispatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeteringServer is the server API for Metering service.
// All implementations must embed UnimplementedMeteringServer
// for forward compatibility
type MeteringServer interface {
	UploadMeteringReading(Metering_UploadMeteringReadingServer) error
	RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error)
	mustEmbedUnimplementedMeteringServer()
}

// UnimplementedMeteringServer must be embedded to have forward compatible implementations.
type UnimplementedMeteringServer struct {
}

func (UnimplementedMeteringServer) UploadMeteringReading(Metering_UploadMeteringReadingServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMeteringReading not implemented")
}
func (UnimplementedMeteringServer) RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordDispatch not implemented")
}
func (UnimplementedMeteringServer) mustEmbedUnimplementedMeteringServer() {}

// UnsafeMeteringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeteringServer will
// result in compilation errors.
type UnsafeMeteringServer interface {
	mustEmbedUnimplementedMeteringServer()
}

func RegisterMeteringServer(s grpc.ServiceRegistrar, srv MeteringServer) {
	s.RegisterService(&Metering_ServiceDesc, srv)
}

func _Metering_UploadMeteringReading_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeteringServer).UploadMeteringReading(&meteringUploadMeteringReadingServer{stream})
}

type Metering_UploadMeteringReadingServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Reading, error)
	grpc.ServerStream
}

type meteringUploadMeteringReadingServer struct {
	grpc.ServerStream
}

func (x *meteringUploadMeteringReadingServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *meteringUploadMeteringReadingServer) Recv() (*Reading, error) {
	m := new(Reading)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Metering_RecordDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeteringServer).RecordDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metering_RecordDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeteringServer).RecordDispatch(ctx, req.(*RecordDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metering_ServiceDesc is the grpc.ServiceDesc for Metering service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metering_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Metering",
	HandlerType: (*MeteringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordDispatch",
			Handler:    _Metering_RecordDispatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMeteringReading",
			Handler:       _Metering_UploadMeteringReading_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metering.proto",
}
