// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: metering.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Metering_FetchMeter_FullMethodName             = "/pb.Metering/FetchMeter"
	Metering_UploadMeteringReadings_FullMethodName = "/pb.Metering/UploadMeteringReadings"
)

// MeteringClient is the client API for Metering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeteringClient interface {
	FetchMeter(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Meter, error)
	UploadMeteringReadings(ctx context.Context, opts ...grpc.CallOption) (Metering_UploadMeteringReadingsClient, error)
}

type meteringClient struct {
	cc grpc.ClientConnInterface
}

func NewMeteringClient(cc grpc.ClientConnInterface) MeteringClient {
	return &meteringClient{cc}
}

func (c *meteringClient) FetchMeter(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Meter, error) {
	out := new(Meter)
	err := c.cc.Invoke(ctx, Metering_FetchMeter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meteringClient) UploadMeteringReadings(ctx context.Context, opts ...grpc.CallOption) (Metering_UploadMeteringReadingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Metering_ServiceDesc.Streams[0], Metering_UploadMeteringReadings_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &meteringUploadMeteringReadingsClient{stream}
	return x, nil
}

type Metering_UploadMeteringReadingsClient interface {
	Send(*Reading) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type meteringUploadMeteringReadingsClient struct {
	grpc.ClientStream
}

func (x *meteringUploadMeteringReadingsClient) Send(m *Reading) error {
	return x.ClientStream.SendMsg(m)
}

func (x *meteringUploadMeteringReadingsClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeteringServer is the server API for Metering service.
// All implementations must embed UnimplementedMeteringServer
// for forward compatibility
type MeteringServer interface {
	FetchMeter(context.Context, *wrapperspb.StringValue) (*Meter, error)
	UploadMeteringReadings(Metering_UploadMeteringReadingsServer) error
	mustEmbedUnimplementedMeteringServer()
}

// UnimplementedMeteringServer must be embedded to have forward compatible implementations.
type UnimplementedMeteringServer struct {
}

func (UnimplementedMeteringServer) FetchMeter(context.Context, *wrapperspb.StringValue) (*Meter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMeter not implemented")
}
func (UnimplementedMeteringServer) UploadMeteringReadings(Metering_UploadMeteringReadingsServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMeteringReadings not implemented")
}
func (UnimplementedMeteringServer) mustEmbedUnimplementedMeteringServer() {}

// UnsafeMeteringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeteringServer will
// result in compilation errors.
type UnsafeMeteringServer interface {
	mustEmbedUnimplementedMeteringServer()
}

func RegisterMeteringServer(s grpc.ServiceRegistrar, srv MeteringServer) {
	s.RegisterService(&Metering_ServiceDesc, srv)
}

func _Metering_FetchMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeteringServer).FetchMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metering_FetchMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeteringServer).FetchMeter(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metering_UploadMeteringReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeteringServer).UploadMeteringReadings(&meteringUploadMeteringReadingsServer{stream})
}

type Metering_UploadMeteringReadingsServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Reading, error)
	grpc.ServerStream
}

type meteringUploadMeteringReadingsServer struct {
	grpc.ServerStream
}

func (x *meteringUploadMeteringReadingsServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *meteringUploadMeteringReadingsServer) Recv() (*Reading, error) {
	m := new(Reading)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Metering_ServiceDesc is the grpc.ServiceDesc for Metering service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metering_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Metering",
	HandlerType: (*MeteringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMeter",
			Handler:    _Metering_FetchMeter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMeteringReadings",
			Handler:       _Metering_UploadMeteringReadings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metering.proto",
}
