// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnergyResource struct {
	ID        string  `json:"id"`
	OwnerName string  `json:"owner_name"`
	Capacity  float64 `json:"capacity"`
}

type Mutation struct {
}

type Query struct {
}
