// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnergyResource struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Producer *User   `json:"producer"`
	Capacity float64 `json:"capacity"`
	Price    float64 `json:"price"`
}

type Mutation struct {
}

type PurchaseEnergy struct {
	ID       string  `json:"id"`
	Capacity float64 `json:"capacity"`
}

type Query struct {
}

type RegisterEnergyResource struct {
	Name       string  `json:"name"`
	ProducerID string  `json:"producer_id"`
	Capacity   float64 `json:"capacity"`
	Price      float64 `json:"price"`
}

type RegisterUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type User struct {
	ID        string            `json:"id"`
	FirstName string            `json:"first_name"`
	LastName  string            `json:"last_name"`
	Resources []*EnergyResource `json:"resources"`
}
