// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnergyResource struct {
	ID       string  `json:"id"`
	OwnerID  string  `json:"owner_id"`
	Capacity float64 `json:"capacity"`
}

type Query struct {
}
