name: org-ca
namespace: org1
image: hyperledger/fabric-ca:1.5.15

tls:
  name: tls-ca

ca:
  name: org1-ca

node:
  type: orderer
  name: orderer0
  secret: orderer0pw

org:
  admin:
    user: orgadmin
    pass: orgadminpw

root:
  user: rcaadmin
  pass: rcaadminpw