apiVersion: batch/v1
kind: Job
metadata:
  name: org-ca-enrollment
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: org-ca-enrollment
          image: {{ .Values.image }}
          env:
            - name: CA_HOST
              value: {{ .Values.name }}.{{ .Values.namespace}}.svc.cluster.local:7054
            - name: FABRIC_CA_CLIENT_HOME
              value: /etc/hyperledger/fabric-ca-client
          args:
            - sh
            - -c
            - |
              sleep 5

              fabric-ca-client enroll \
                -u https://{{ .Values.root.user }}:{{ .Values.root.pass }}@${CA_HOST} \
                --tls.certfiles tls-root-cert/tls-ca-cert.pem \
                --mspdir {{ .Values.name }}/{{ .Values.root.user }}/msp \
                -d

              echo "Org CA Admin was enrolled"

              fabric-ca-client register \
                -d \
                --id.name {{ .Values.org.admin.user }} \
                --id.secret {{ .Values.org.admin.pass }} \
                -u https://${CA_HOST} \
                --mspdir {{ .Values.name }}/{{ .Values.root.user }}/msp \
                --id.type admin \
                --tls.certfiles tls-root-cert/tls-ca-cert.pem

              echo "Org Admin was registered"

              fabric-ca-client enroll \
                -d \
                -u https://{{ .Values.org.admin.user }}:{{ .Values.org.admin.pass }}@${CA_HOST} \
                --mspdir {{ .Values.namespace }}/msp \
                --csr.hosts *.{{ .Values.namespace }}.svc.cluster.local,localhost \
                --tls.certfiles tls-root-cert/tls-ca-cert.pem

              echo "Org Admin was enrolled"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-client
              name: tls-ca-client-root
      restartPolicy: Never
      volumes:
        - name: tls-ca-client-root
          persistentVolumeClaim:
            claimName: {{ .Values.tls.name }}-client-pvc